#! /bin/bash
# this file should be placed in /etc/network/if-up.d/ and /etc/network/if-post-down.d/
sleep 3
route del -net 0.0.0.0 netmask 0.0.0.0 gw 192.168.1.1
route del -net 0.0.0.0 netmask 0.0.0.0 gw 192.168.1.1
